name: 'Deploy service'
description: 'Deploy service to EKS cluster'
inputs:
  AWS_ACCESS_KEY:
    description: 'AWS access key'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secret access key'
    required: true
  AWS_REGION:
    description: 'AWS region'
    required: true
  KUBE_CONFIG_DATA:
    description: 'Kubernetes config for authenticating to EKS API'
    required: true
  APP_VERSION:
    description: 'Application version that gets deployed'
    required: true
  KUBE_NAMESPACE:
    description: 'Kubernetes namespace to where application gets deployed'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configure kubectl context
      shell: bash
      env:
        KUBE_CONFIG: ${{ inputs.KUBE_CONFIG_DATA }} 
      run: |
        echo "$KUBE_CONFIG" | base64 -d > /tmp/config
        echo "KUBECONFIG=/tmp/config" >> $GITHUB_ENV

    - name: Deploy to EKS cluster
      uses: swdotcom/update-and-apply-kubernetes-configs@v1
      env:
        APP_VERSION: ${{ inputs.APP_VERSION }}
        KUBE_NAMESPACE: ${{ inputs.KUBE_NAMESPACE }}
      with:
        namespace: dev
        k8-config-file-paths: |
          k8s/service.yaml
          k8s/deployment.yaml
          k8s/ingress.yaml    